//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afdekmateriaal
    {
        public int AfdekID { get; set; }
        public string Naam_afdekmateriaal { get; set; }
        public string Omschrijving { get; set; }
        public string Locatie { get; set; }
        public string Info { get; set; }
        public string Leverancier { get; set; }
        public Nullable<decimal> Prijs { get; set; }
        public string Afdekmateriaalfoto { get; set; }
        public string Magazijn { get; set; }
    }
}
