//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSAInleggen
    {
        public int InlegID { get; set; }
        public string Netnaam { get; set; }
        public Nullable<int> Inlegnetnummer { get; set; }
        public string Inlegdoor { get; set; }
        public string InlegOpmerkingen { get; set; }
        public Nullable<System.DateTime> Inlegdatum { get; set; }
        public Nullable<System.DateTime> Inlegtijd { get; set; }
        public Nullable<System.DateTime> InlegExpiratiedatum { get; set; }
        public Nullable<int> Gewicht { get; set; }
        public Nullable<int> Verrichtingid { get; set; }
        public string OKopmerkingen { get; set; }
        public Nullable<System.DateTime> CSAdataankomst { get; set; }
        public Nullable<System.DateTime> CSAtijdaankomst { get; set; }
        public string CSAmedewaankomst { get; set; }
        public string CSAopmaankomst { get; set; }
        public bool CSAopmokingel { get; set; }
        public Nullable<int> Charge { get; set; }
        public Nullable<int> Autoclaaf { get; set; }
        public bool Dustcover { get; set; }
        public Nullable<System.DateTime> Dutcoverdat { get; set; }
        public Nullable<System.DateTime> Sterilisatiedatum { get; set; }
        public Nullable<System.DateTime> Sterilisatietijd { get; set; }
        public Nullable<int> TempID { get; set; }
    }
}
