//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gebruiker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gebruiker()
        {
            this.Netten = new HashSet<Netten>();
        }
    
        public int ID { get; set; }
        public Nullable<int> RolID { get; set; }
        public string Inlognaam { get; set; }
        public string Volledigenaam { get; set; }
        public string Wachtwoord { get; set; }
        public string Geslacht { get; set; }
        public string Adres { get; set; }
        public string Postcode { get; set; }
        public string Plaats { get; set; }
        public string Email { get; set; }
        public string Functie { get; set; }
        public Nullable<System.DateTime> GeboorteDatum { get; set; }
        public string TelNr { get; set; }
        public string TelNrMobiel { get; set; }
        public bool Aktief { get; set; }
        public bool Gelijkafdrukken { get; set; }
        public bool Afdrukkenvlgsinleggen { get; set; }
        public Nullable<bool> GebruikRFID { get; set; }
        public Nullable<bool> GebruikWeegschaal { get; set; }
        public Nullable<System.DateTime> Startdatum { get; set; }
        public Nullable<System.DateTime> Einddatum { get; set; }
        public Nullable<System.DateTime> Laatsteinlogdat { get; set; }
        public Nullable<System.DateTime> Laatsteinlogtim { get; set; }
        public string ExtraInfo { get; set; }
        public bool MomenteelIngelogd { get; set; }
    
        public virtual Roll Roll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Netten> Netten { get; set; }
    }
}
