//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrumenten
    {
        public int ID { get; set; }
        public Nullable<int> Categorie { get; set; }
        public string Instrumentnaam { get; set; }
        public Nullable<int> MaxTemp { get; set; }
        public Nullable<int> MinTemp { get; set; }
        public Nullable<int> LeverancierID { get; set; }
        public string Bestelnummer { get; set; }
        public string Bijzonderheden { get; set; }
        public Nullable<int> Specialisme { get; set; }
        public Nullable<decimal> Gewicht { get; set; }
        public Nullable<System.DateTime> Datumwijziging { get; set; }
        public Nullable<int> GewijzigddoorID { get; set; }
        public Nullable<decimal> Kost { get; set; }
        public string Image { get; set; }
        public string VoorraadLocatie { get; set; }
        public Nullable<int> AantalVoorraad { get; set; }
    
        public virtual Categorie Categorie1 { get; set; }
    }
}
