//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leveranciers
    {
        public int LEVID { get; set; }
        public string Naam { get; set; }
        public string Adres { get; set; }
        public string Plaats { get; set; }
        public string Vertegenwoordiger { get; set; }
        public string Telefoonnummer { get; set; }
        public string TelefoonnummerMobiel { get; set; }
        public string Fax { get; set; }
        public string Specialisatie { get; set; }
        public string Postcode { get; set; }
        public string Website { get; set; }
        public string Emailadres { get; set; }
        public Nullable<int> Crediteurnummer { get; set; }
        public string Klantnummer { get; set; }
    }
}
