//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ERBAEntities : DbContext
    {
        public ERBAEntities()
            : base("name=ERBAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C1tempinstrumenten> C1tempinstrumenten { get; set; }
        public virtual DbSet<Afdekmateriaal> Afdekmateriaal { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<CSAInleggen> CSAInleggen { get; set; }
        public virtual DbSet<Employee2T> Employee2T { get; set; }
        public virtual DbSet<Fotos> Fotos { get; set; }
        public virtual DbSet<Gebruiker> Gebruiker { get; set; }
        public virtual DbSet<Instrserienummers> Instrserienummers { get; set; }
        public virtual DbSet<Instrumenten> Instrumenten { get; set; }
        public virtual DbSet<Klaarzetten> Klaarzetten { get; set; }
        public virtual DbSet<KplTblAfdek> KplTblAfdek { get; set; }
        public virtual DbSet<Leveranciers> Leveranciers { get; set; }
        public virtual DbSet<luLocatie> luLocatie { get; set; }
        public virtual DbSet<Media> Media { get; set; }
        public virtual DbSet<Medicijnen> Medicijnen { get; set; }
        public virtual DbSet<NetInstrument> NetInstrument { get; set; }
        public virtual DbSet<Netnummers> Netnummers { get; set; }
        public virtual DbSet<Netten> Netten { get; set; }
        public virtual DbSet<Operatiekamers> Operatiekamers { get; set; }
        public virtual DbSet<Programmainstellingen> Programmainstellingen { get; set; }
        public virtual DbSet<Reparaties> Reparaties { get; set; }
        public virtual DbSet<Roll> Roll { get; set; }
        public virtual DbSet<Setting> Setting { get; set; }
        public virtual DbSet<Specialismen> Specialismen { get; set; }
        public virtual DbSet<SubLLocaties> SubLLocaties { get; set; }
        public virtual DbSet<tblStamGeg> tblStamGeg { get; set; }
        public virtual DbSet<Temperatuur> Temperatuur { get; set; }
        public virtual DbSet<TempInstrInNet_0> TempInstrInNet_0 { get; set; }
        public virtual DbSet<TempInstrInNet_1> TempInstrInNet_1 { get; set; }
        public virtual DbSet<TempInstrInNet_2> TempInstrInNet_2 { get; set; }
        public virtual DbSet<TempInstrInNet_3> TempInstrInNet_3 { get; set; }
        public virtual DbSet<TempInstrInNet_4> TempInstrInNet_4 { get; set; }
        public virtual DbSet<TempInstrInNet_5> TempInstrInNet_5 { get; set; }
        public virtual DbSet<TempInstrInNet_6> TempInstrInNet_6 { get; set; }
        public virtual DbSet<TempInstrInNet_7> TempInstrInNet_7 { get; set; }
        public virtual DbSet<TempInstrInNet_8> TempInstrInNet_8 { get; set; }
        public virtual DbSet<TempInstrInNet_9> TempInstrInNet_9 { get; set; }
        public virtual DbSet<tempOperatiekamers> tempOperatiekamers { get; set; }
        public virtual DbSet<Users_OLD> Users_OLD { get; set; }
        public virtual DbSet<VerrichtingenGebruikteNettenOK> VerrichtingenGebruikteNettenOK { get; set; }
        public virtual DbSet<VerrichtingenStartOpdeOK> VerrichtingenStartOpdeOK { get; set; }
        public virtual DbSet<Verwijzingklaarzettenals> Verwijzingklaarzettenals { get; set; }
        public virtual DbSet<Werkplekken> Werkplekken { get; set; }
        public virtual DbSet<KplTblMedicijn> KplTblMedicijn { get; set; }
        public virtual DbSet<KplTblNet> KplTblNet { get; set; }
        public virtual DbSet<Locaties> Locaties { get; set; }
        public virtual DbSet<Zichtorders> Zichtorders { get; set; }
    
        public virtual ObjectResult<spGetNetByID_Result> spGetNetByID(Nullable<int> netID)
        {
            var netIDParameter = netID.HasValue ?
                new ObjectParameter("NetID", netID) :
                new ObjectParameter("NetID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetNetByID_Result>("spGetNetByID", netIDParameter);
        }
    
        public virtual ObjectResult<spGetNetInstruments_Result> spGetNetInstruments(Nullable<int> netID)
        {
            var netIDParameter = netID.HasValue ?
                new ObjectParameter("NetID", netID) :
                new ObjectParameter("NetID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetNetInstruments_Result>("spGetNetInstruments", netIDParameter);
        }
    
        public virtual ObjectResult<spGetNetten_Result> spGetNetten()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetNetten_Result>("spGetNetten");
        }
    
        public virtual int spSearchNetten()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSearchNetten");
        }
    }
}
