//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetInstrument
    {
        public int ID { get; set; }
        public int NETID { get; set; }
        public int INSID { get; set; }
        public Nullable<int> AantalINS { get; set; }
        public bool Aan_Speld { get; set; }
        public Nullable<int> Inlegvolgnummer { get; set; }
    }
}
