//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Netnummers
    {
        public int NetnoID { get; set; }
        public Nullable<int> NetID { get; set; }
        public Nullable<int> Nummer { get; set; }
        public Nullable<int> Netstatus { get; set; }
        public Nullable<System.DateTime> Netstatusdatum { get; set; }
        public Nullable<System.DateTime> Netstatustijd { get; set; }
        public string Bijzonderheden { get; set; }
        public Nullable<int> tmpverrid { get; set; }
        public string ExtraInfoNet { get; set; }
    }
}
