//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operatiekamers
    {
        public int OKID { get; set; }
        public string Operatiekamer { get; set; }
        public Nullable<System.DateTime> geldigvanaf { get; set; }
        public Nullable<System.DateTime> geldigtot { get; set; }
        public string code { get; set; }
    }
}
