//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reparaties
    {
        public int RepID { get; set; }
        public Nullable<int> NetID { get; set; }
        public Nullable<int> Instrument { get; set; }
        public Nullable<int> Serienummer { get; set; }
        public string Klacht { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string AfgehandeldBy { get; set; }
        public Nullable<int> ReparatieBy { get; set; }
        public Nullable<int> Firmanaam { get; set; }
        public bool Net_Uit_Roulatie { get; set; }
        public Nullable<System.DateTime> DatumRetour { get; set; }
        public string AangenomenBy { get; set; }
        public Nullable<decimal> Kosten { get; set; }
        public bool Afgeschreven { get; set; }
        public bool VervangendInstrument { get; set; }
        public bool Verzonden { get; set; }
    }
}
