//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int ID { get; set; }
        public string SectionKey { get; set; }
        public string SubSection1 { get; set; }
        public string SubSection2 { get; set; }
        public string Sleutel { get; set; }
        public string Waarde { get; set; }
    }
}
