//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubLLocaties
    {
        public int ID { get; set; }
        public Nullable<int> LocatieID { get; set; }
        public Nullable<int> AutoclaafGoedOFafkeuren { get; set; }
        public string Code { get; set; }
        public string Naam { get; set; }
        public string Type { get; set; }
        public string Bijzonderheden { get; set; }
        public Nullable<int> Leverancier { get; set; }
        public Nullable<System.DateTime> Vervallen { get; set; }
    }
}
