//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStamGeg
    {
        public int ID { get; set; }
        public string C1RECORD { get; set; }
        public string BEpad { get; set; }
        public Nullable<short> VerNr { get; set; }
        public Nullable<System.DateTime> VerDtm { get; set; }
    }
}
