//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temperatuur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Temperatuur()
        {
            this.Netten = new HashSet<Netten>();
        }
    
        public int TempID { get; set; }
        public string AutoclaafType { get; set; }
        public Nullable<int> Temprature { get; set; }
        public Nullable<int> MinTemperatuur { get; set; }
        public Nullable<int> MaxTemperatuur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Netten> Netten { get; set; }
    }
}
