//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_OLD
    {
        public int ID { get; set; }
        public Nullable<int> UserGroupID { get; set; }
        public string EmployeeNumber { get; set; }
        public string ForeName { get; set; }
        public string FamilyName { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Aktief { get; set; }
        public Nullable<bool> RapportAccess { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string TelNr1 { get; set; }
        public string TelNr2 { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public string Skype { get; set; }
        public string TokenID { get; set; }
        public string ExtraInfo { get; set; }
    
        public virtual Users_OLD Users_OLD1 { get; set; }
        public virtual Users_OLD Users_OLD2 { get; set; }
    }
}
