//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerrichtingenGebruikteNettenOK
    {
        public int VerrID { get; set; }
        public Nullable<System.DateTime> okdatum { get; set; }
        public Nullable<System.DateTime> oktijd { get; set; }
        public string operatiekamer { get; set; }
        public string verrichting { get; set; }
        public string instrumenterende { get; set; }
        public string omloop { get; set; }
        public Nullable<int> pinnr { get; set; }
    }
}
