//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerrichtingenStartOpdeOK
    {
        public int VerrID { get; set; }
        public Nullable<int> pinnr { get; set; }
        public string PatientNaam { get; set; }
        public Nullable<System.DateTime> Geboortedatum { get; set; }
        public string Anesthesietechniek { get; set; }
        public Nullable<System.DateTime> oktijd { get; set; }
        public Nullable<System.DateTime> okdatum { get; set; }
        public string operatiekamer { get; set; }
        public string verrichting { get; set; }
        public Nullable<System.DateTime> tijdinLeiding { get; set; }
        public Nullable<System.DateTime> tijdbeginOK { get; set; }
        public Nullable<System.DateTime> tijdeindeOK { get; set; }
        public Nullable<System.DateTime> tijduitleiding { get; set; }
        public Nullable<System.DateTime> tijduitdeOK { get; set; }
        public string ingreepLigging { get; set; }
        public string instrumenterende { get; set; }
        public string omloop { get; set; }
        public string Anesthenist { get; set; }
        public string Anesthesiemedewerker { get; set; }
        public string Operateur { get; set; }
        public string OperateurAssistent { get; set; }
        public string InstrumentenGeteld { get; set; }
        public string DisposablesGeteld { get; set; }
        public string NaaldenHectingGeteld { get; set; }
        public string GazenGeteld { get; set; }
        public string Inplantaten { get; set; }
    }
}
